services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Monta o init.sql para inicialização
    networks:
      - backend-network

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  db_data:
