-- Criação da tabela (se ainda não existir)
CREATE TABLE IF NOT EXISTS piadas (
    id SERIAL PRIMARY KEY,
    setup TEXT NOT NULL,
    punchline TEXT NOT NULL
);

-- Inserção das piadas
INSERT INTO piadas (setup , punchline) VALUES
('Por que o livro de matemática se suicidou?', 'Porque tinha muitos problemas.'),
('Qual é o cúmulo da paciência?', 'Esperar o tempo passar.'),
('O que a parede falou para o espelho?', 'Te vejo mais tarde!'),
('Qual é o animal mais antigo?', 'A zebra, porque é em preto e branco.'),
('Por que o sapato não vai para a escola?', 'Porque ele já tem uma soleira.'),
('Como se chama um boi sem pernas?', 'Picanha!'),
('Por que o computador foi ao médico?', 'Porque estava com vírus.'),
('Qual é o objeto mais vaidoso?', 'O espelho, porque está sempre se olhando.'),
('Como o elefante se esconde na árvore?', 'Pintando a unha de verde.'),
('Qual é o lugar mais quente da escola?', 'A sala de aula, porque tem muito calor.'),
('Por que o menino levou uma escada para a escola?', 'Para chegar no ensino superior.'),
('O que o tomate foi fazer no banco?', 'Tirar extrato.'),
('Qual é o contrário de “morango”?', '“Não morango”.'),
('Como o pescador sabe que está na beira da praia?', 'Porque está no mar.'),
('Por que o cavalo foi ao médico?', 'Porque estava com febre.'),
('Qual é a fruta que anda com um copo na mão?', 'A laranja.'),
('Por que o livro de geografia nunca se perde?', 'Porque sempre está em um lugar definido.'),
('O que o esqueleto disse para o outro?', '“Você está com a cara pálida!”'),
('Qual é o animal que anda com a cabeça para baixo?', 'A cobra.'),
('Por que o livro de história não pode ficar triste?', 'Porque ele tem um passado feliz.'),
('Como o corvo chama seu filho?', 'Filhote.'),
('Qual é a comida que nunca envelhece?', 'O queijo, porque está sempre maturando.'),
('Por que o sol nunca entra na escola?', 'Porque ele já está sempre no céu.'),
('Qual é o carro que nunca se perde?', 'O carro de polícia.'),
('Por que a vaca foi para o espaço?', 'Para ver a Via Láctea.'),
('Como se chama um cachorro que faz mágica?', 'Um cachorro mágico.'),
('Qual é a fruta que nunca está madura?', 'A pera.'),
('Por que o coelho não gosta de filmes de terror?', 'Porque ele fica com medo das cenouras.'),
('O que o pato falou para a pata?', '“Vamos nadar?”'),
('Qual é a parte do corpo que mais se exercita?', 'A língua, porque está sempre falando.'),
('Por que o relógio foi ao dentista?', 'Porque estava com cárie.'),
('O que o peixe disse para a peixinha?', '“Você é a minha água!”'),
('Qual é o mês mais curto?', 'Fevereiro.'),
('Por que o jardim fica feliz?', 'Porque ele está sempre em flor.'),
('Como o cachorro se despede?', '“Au revoir!”'),
('Qual é o estado mais sujo?', 'O estado de “lixo”.'),
('Por que a vaca foi ao espaço?', 'Para ver a lua.'),
('Como o pássaro sabe que vai chover?', 'Porque ele sente o clima.'),
('Qual é o prato que nunca enche?', 'O prato de comida do cachorro.'),
('Por que a abelha sempre tem uma agenda?', 'Porque ela está sempre ocupada.'),
('Qual é o animal que usa óculos escuros?', 'O “gato-cool”.'),
('Por que o passarinho não usa Facebook?', 'Porque ele já tem Twitter.'),
('Qual é a comida preferida do livro?', 'O capítulo.'),
('Por que o batom não pode entrar no banco?', 'Porque não pode fazer depósito.'),
('Como se chama um cavalo que gosta de teatro?', 'Um cavalo dramático.'),
('Qual é o animal que está sempre no trabalho?', 'A formiga.'),
('Por que a geladeira é uma ótima cantora?', 'Porque ela tem um ótimo “frio”.'),
('O que o morcego falou para o outro?', '“Vamos dar uma volta no escuro!”'),
('Qual é a fruta que é um perigo?', 'A laranja, porque pode te “espremer”.');