- hosts: backend
  tasks:
    - name: Clonar ou atualizar o repositório do backend
      git:
        repo: "https://github.com/Gabrielzg1/cloud-docker.git"
        dest: /backend
        version: main

    - name: Subir containers com Docker Compose (Node.js + PostgreSQL)
      shell: docker-compose up -d
      args:
        chdir: /home/gabriel/cloud-docker/backend
