- hosts: frontend
  tasks:
    - name: Clonar ou atualizar o repositório do frontend
      git:
        repo: "https://github.com/Gabrielzg1/cloud-docker.git"
        dest: /frontend
        version: main

    - name: Subir o container do frontend com Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/gabriel/cloud-docker/frontend
