name: Deploy Projeto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar webhook para deploy
        run: |
          curl -X POST http://SEU_SERVIDOR:5000/webhook \
          -H 'Content-Type: application/json' \
          -d '{"repository": {"name": "cloud-docker"}}'
