name: Deploy Projeto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar webhook para deploy
        run: |
          curl -X POST https://24b2-2804-1b3-a801-3c9e-95-433a-1b7f-2d01.ngrok-free.app /webhook \
          -H 'Content-Type: application/json' \
          -d '{"repository": {"name": "cloud-docker"}}'
