name: Run Tests with Frontend and Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose (CLI-based)
        run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Wait for Backend and Frontend
        run: |
          echo "Waiting for services to start..."
          until curl -s http://localhost:3000/piada; do
            echo "Waiting for backend..."
            sleep 5
          done
          until curl -s http://localhost:8080; do
            echo "Waiting for frontend..."
            sleep 5
          done
          echo "Services are ready!"

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Shut Down Docker Compose
        if: always()
        run: docker compose down
