name: Run Tests with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Instalar dependências do projeto
      - name: Install Dependencies
        run: npm install

      # Configurar Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Subir serviços com Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d

      # Esperar os serviços ficarem prontos
      - name: Wait for Backend and Frontend
        run: |
          echo "Waiting for Backend to start..."
          until curl -s http://localhost:3000/piada; do
            echo "Waiting for Backend..."
            sleep 5
          done
          echo "Backend is ready!"
          echo "Waiting for Frontend to start..."
          until curl -s http://localhost:8080; do
            echo "Waiting for Frontend..."
            sleep 5
          done
          echo "Frontend is ready!"

      # Instalar navegadores do Playwright
      - name: Install Playwright Browsers
        run: npx playwright install

      # Executar os testes
      - name: Run Playwright Tests
        run: npx playwright test

      # Derrubar os serviços ao final
      - name: Shut Down Docker Compose
        run: docker-compose down
