name: Run Tests with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Configurar Docker Compose usando a ação do Medium
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose
        run: docker-compose up -d

      # Aguardar serviços ficarem prontos
      - name: Wait for Backend and Frontend
        run: |
          echo "Waiting for Backend to start..."
          until curl -s http://localhost:3000/piada; do
            echo "Waiting for Backend..."
            sleep 5
          done
          echo "Backend is ready!"
          echo "Waiting for Frontend to start..."
          until curl -s http://localhost:8080; do
            echo "Waiting for Frontend..."
            sleep 5
          done
          echo "Frontend is ready!"

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      # Derrubar os serviços ao final
      - name: Shut Down Docker Compose
        run: docker-compose down
