name: Run Tests with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Configura o Docker Compose usando a ação oficial
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose Up
        uses: peter-evans/docker-compose-actions-workflow@v2
        with:
          up: docker-compose.yml
          run-wait: |
            echo "Waiting for Backend to start..."
            until curl -s http://localhost:3000/piada; do
              echo "Waiting for Backend..."
              sleep 5
            done
            echo "Backend is ready!"
            echo "Waiting for Frontend to start..."
            until curl -s http://localhost:8080; do
              echo "Waiting for Frontend..."
              sleep 5
            done
            echo "Frontend is ready!"

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      # Derruba os serviços ao final
      - name: Run Docker Compose Down
        uses: peter-evans/docker-compose-actions-workflow@v2
        with:
          down: true
